import { defineConfig } from 'orval';

// Schemas-only Zod generation from the committed OpenAPI snapshot (D1: orval, plan U03).
// oneOf+discriminator emits zod.union of strict kind-literal objects — accepts/rejects the
// exact same payload set as z.discriminatedUnion; TS narrowing on .kind works identically.
export default defineConfig({
  sidecar: {
    input: { target: '../openapi.json' },
    output: {
      client: 'zod',
      mode: 'single',
      target: './src/generated/zod.ts',
      override: {
        header: (info) => [
          `Generated by orval from openapi.json - DO NOT EDIT (spec: ${info.title} v${info.version})`,
          'Regenerate: sidecar/scripts/generate_zod.sh',
        ],
        zod: {
          strict: { param: true, query: true, header: true, body: true, response: true },
          generate: { param: true, query: true, header: true, body: true, response: true },
          generateReusableSchemas: true,
        },
      },
    },
  },
});
